import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import { useForm } from "react-hook-form";
import { Button, Form, Input } from "react-daisyui";
import { useAtom } from "jotai";
import { userIdAtom } from "../index";
import { useEffect } from "react";
import { useRouter } from "next/router";

const ChattingPage: NextPage = () => {
  const [userId, setUserId] = useAtom(userIdAtom);
  const router = useRouter();
  const dateId = router.query.dateId as string;
  const getDateUsersQuery = trpc.useQuery(["dates.getDateUsers", { dateId }]);

  let otherUserName = "";

  if (getDateUsersQuery.data) {
    const isCurrentlySinkUser = getDateUsersQuery.data.sinkUserId === userId;
    otherUserName = isCurrentlySinkUser
      ? getDateUsersQuery.data.sourceUser.name
      : getDateUsersQuery.data.sinkUser.name;
  }

  return (
    <>
      <Head>
        <title>
          {(otherUserName && `Chatting with ${otherUserName}`) ||
            "Connecting to a user..."}
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-6 items-center justify-center min-h-screen p-4">
        <h3 className="text-xl">{(otherUserName && `Chatting with ${otherUserName}`) ||
            "Chatting with a user"}</h3>
        <div>
          <img src="/puff.svg" />
        </div>
      </main>
    </>
  );
};

export default ChattingPage;
