import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useForm } from "react-hook-form";
import { Button, Form, Input } from "react-daisyui";
import { useRouter } from "next/router";
import { atom, useAtom } from "jotai";

type RegisterForm = {
  name: string;
  contactInfo: string;
};

export const userIdAtom = atom("");

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<RegisterForm>();

  const [userId, setUserId] = useAtom(userIdAtom);

  const createUser = trpc.useMutation("users.createUser", {
    onSuccess: (data) => {
      setUserId(data.id);
      router.push("/waiting");
    },
  });
  const router = useRouter();

  const onSubmit = async (data: RegisterForm) => {
    await createUser.mutateAsync(data);
  };

  return (
    <>
      <Head>
        <title>Speed Date</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-6 items-center justify-center min-h-screen p-4">
        <h3 className="text-xl">Join a Speed Dating Session</h3>
        <Form
          onSubmit={handleSubmit(onSubmit)}
          className="lg:w-1/3 w-2/3 flex flex-col gap-4"
        >
          <div>
            <Form.Label title="Name"></Form.Label>
            <Input
              {...register("name", { required: true })}
              className="w-full"
              placeholder="Your display name"
            />
            {errors.name && (
              <span className="text-red-500">This field is required</span>
            )}
          </div>
          <div>
            <Form.Label title="Contact Info"></Form.Label>
            <Input
              {...register("contactInfo", { required: true })}
              className="w-full"
              placeholder="Facebook profile, WhatsApp, e-mail, etc."
            />
            {errors.contactInfo && (
              <span className="text-red-500">This field is required</span>
            )}
          </div>
          <Button className="m-auto" type="submit" color="primary">
            JOIN SESSION
          </Button>
        </Form>
      </main>
    </>
  );
};

export default Home;
